sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: MNaE8dO/kcxT/Y9sEIBJWH4kwuudW2vF9pr96KlvZzMaUcCnQmdYwAv5ppH59k6rDMKY6ZusHlWmCz6JW6uGK9MEYYBeyIyDSupZ63o6Bbt4m6bvGKI9hCzkei3st4sQh9NWms2Mq/NeVhcXm6SCCTCq+ah5PSpHTBlZ/mF7YGQ7/ofhI/Sgu5/VsNP/j51EN9Pmk+KfHo5KILzQvQw9EqQ6Rivyxn99dEErctQbOP7DEBQMbGXraJElblkdbfvj/yX+K690e2NmbTEWAx+AyuvK1EpFiZZh/XQEyi2fK1zGBmX5JjTDDYIL4e98yOM5WRIDQt3Iz4Im1lHahs5nyexmGA+S5ZgfNnNX0OH0mqiFTC2SntYqclsWN7EmLCQ29xgR1+Mts8THwIpfNLzoX3INjmWTtOQWNtuGT3R5B+RBYhwwLmP/s/SavbPQUXfjlpbPRcd6OVCEQbsC0/PJZwcMsPUw86rXvpnlOWopD1ValPqJjHfEbQ9jRPfSyk57iYxrmzRYIKQhdanOancEwhtSN3zDbclu3iAPlAJSPiRwg90VKod7fum6vp0f97pvbC1waCEb5BB6saN434UI2vqDK9gMq6U6F3Oi5KL9PPEB50IYqd1Mqfvz37SMXZHzR7oqApXOMEG59a3+4pCeVbzahS2UwsHGlLpaC5BHnow=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Belton-Estate_4969
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy